apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::672761589226:role/GitHubAction-AssumeRoleWithAction
      username: Sandeep
      groups:
        - system:masters